### ISSUE TITLE
Compile fails - EventEmitter is removed from Node.js

### ISSUE THREAD

**Issue by olvesh** [liesen/libspotify-node#5]
I found this little project which looks like just the thing I need for my current pet project.

But the sources doesn't compile any more -  all classes subclassing EventEmitter will not compile as EventEmitter is removed from node.js.

Found this link where node-ncurses fixed the same problem.
https://groups.google.com/group/nodejs/browse_thread/thread/ae6bc0e37e2edc39?fwc=1

I could have seen if I can make it work myself, but have not been into c++ since 1999-something :-), and not into the c-parts of node either..

**Comment by olvesh** [comment]
Against 0.6.6 of node.js

**Comment by liesen** [comment]
I'm afraid I haven't kept this project up to date, so some things are likely broken. At a first glance, the proposed fix (from node-ncurses) seem non-trivial, but I might be mistaken: may I suggest that you give it a shot?

**Comment by olvesh** [comment]
Sure, I should brush up on c++ anyway - hoped you had some clues though :-) I'll fork and see what I can come up with.
